colorlessenergy/lastpad

README.md
add information about the project and about the creators as per issue #7
=> update readme to explain the project as per issue #7

frontend/.gitignore, frontend/src/layout/Layout.js
as per issue #9 
add HashRouter
=> add HashRouter as per issue #9

backend/app.js, backend/controllers/note.js, backend/models/schemas/note.js, backend/models/schemas/user.js, backend/routes/authRouter.js, backend/routes/noteRouter.js
add as per issue #11 
* controller to create a note to mongodb
* schema for a note
* a route to '/note' to create a note
* reference to Notes in User schema
=> add functionality to back end to create a note #11

backend/.gitignore, backend/controllers/note.js, backend/routes/noteRouter.js
as per #13
add:
* getNotes controller to return a user's notes
* route to get a user's notes
=> as per #13 add route to get a user's notes

backend/controllers/note.js, backend/routes/noteRouter.js
add as per issue #15
* remove a note from the note collection based on the id
=> delete a single note from mongodb #15

package.json
=> add package with install scripts for heroku

frontend/src/container/Notes/NotePage.js, frontend/src/layout/Layout.js, frontend/src/store/actions/auth.js, frontend/src/store/actions/note.js, frontend/src/store/reducers/noteReducer.js
as per #23
Add:
* NotePage.js which is the page that shows a single note
* Action creator for fetching a note from the server
Update:
* Redux store
=> add functionality to view a single note as per #23

frontend/src/container/Notes/Notes.module.css, frontend/src/index.css
as per #33 
Update:
* Home page css
=> update home page css as per #33

backend/routes/authRouter.js, frontend/src/component/Home/Home.js, frontend/src/container/Login/Login.js, frontend/src/container/NavBar/NavBar.js, frontend/src/container/Notes/Notes.js, frontend/src/index.js, frontend/src/layout/Layout.js, frontend/src/store/actions/auth.js, frontend/src/store/reducers/authReducer.js
add route guarding to certain links. This is done by setting a property to keep track of the state of a user that is logged in in Redux. This property is altered every time the user login, logout or a page is initially loaded. This property is used to redirect in React.
add a navbar that shows the links to register, login and home page if the user is logged out otherwise show create, home page and logout links.
add redux for logout and checking if a user is logged in.
as per issue #35
=> setup navbar with route guarding

frontend/src/container/NavBar/NavBar.js, frontend/src/container/NavBar/NavBar.module.css, frontend/src/index.css
add as per issue #44 
* implement the navbar design
* classes to navbar component
* css
* box-sizing property to every element
=> add box-sizing property and implement navbar design

package.json
=> update the start script in the package.json for azure

frontend/src/component/Buttons/Buttons.js, frontend/src/component/Buttons/Buttons.module.css, frontend/src/container/Notes/NotePage.js
add as per issue #48 
* functional component that has buttons to delete, view all and edit a note
* move the buttons from the bottom of the notepage to the top
=> add a functional component to display buttons

frontend/src/component/Buttons/Buttons.js, frontend/src/component/Buttons/Buttons.module.css, frontend/src/container/Notes/CreateNote/CreateNote.js, frontend/src/container/Notes/CreateNote/CreateNote.module.css, frontend/src/container/Notes/UpdateNote/UpdateNote.js, frontend/src/index.css, frontend/src/store/actions/index.js
add as per issue #50 
* css for the update and create component
* add classes to html
=> add styles to the update and create component as per issue #50

frontend/src/container/Login/Login.js, frontend/src/container/Register/Register.js, frontend/src/container/Register/Register.module.css, frontend/src/index.js
add as per issue #54 
* implement the design for login page
* form validation for the login form
=> add form validation and implement design for login page

frontend/src/component/Home/Home.js, frontend/src/container/NavBar/NavBar.js, frontend/src/container/Notes/CreateNote/CreateNote.js, frontend/src/container/Notes/Notes.js, frontend/src/shared/online-check.js, frontend/src/store/actions/auth.js, frontend/src/store/actions/index.js, frontend/src/store/actions/note.js
add as per issue #58 
* notes to localStorage if the user is offline
*  a setInterval to check if the user is online every 5 seconds to update a note
=> create a note offline as per issue #58

frontend/src/shared/online-check.js, frontend/src/store/actions/note.js
as per #60 
add:
* offline delete note functionality in deleteUserNoteAction
* check to update deleted db notes in createOfflineToOnline
=> as per #60 add functionality to delete a note offline

frontend/src/container/Notes/Notes.js
add as per issue #66 
* filter notes with an input text box
=> filter notes with an input by title and content

backend/app.js, backend/package.json
replace memorystore used in express session by default to [connect-mongo](https://www.npmjs.com/package/connect-mongo)
=> replace the memorystore used by default

backend/app.js, backend/config/config_prod.js, backend/controllers/note.js, backend/controllers/user.js, backend/package.json, backend/routes/authRouter.js, frontend/src/store/reducers/noteReducer.js
add as per issue #70 
* used [crpytr](https://www.npmjs.com/package/cryptr) library for encryption and decryption that uses crypto which is built into node
* encrypt notes when updating and creating them
* decrypt notes when fetching for them
=> encrypt user notes when creating and updating them

package.json
add necessary scripts to deploy to heroku
=> update package.json file to deploy on heroku

frontend/src/container/NavBar/NavBar.js, frontend/src/container/NavBar/NavBar.module.css, frontend/src/container/Notes/CreateNote/CreateNote.module.css, frontend/src/container/Notes/NotePage.js, frontend/src/container/Notes/Notes.module.css, frontend/src/container/Notes/UpdateNote/UpdateNote.js, frontend/src/container/Register/Register.module.css, frontend/src/index.css
update as per issue #77 
* layout for navbar 
* styles for notes
=> update styles for notes and navbar

frontend/package.json, frontend/src/container/Login/Login.js, frontend/src/container/Register/Register.module.css, frontend/src/store/actions/auth.js, frontend/src/store/reducers/authReducer.js
closes #79 
reuse the login action that existed and passed in the credentials to the guest login
add
* a button to login as guest
* css to style the button
=> add a button to login as guest

frontend/src/container/Login/Login.js, frontend/src/container/NavBar/NavBar.module.css, frontend/src/container/Notes/CreateNote/CreateNote.js, frontend/src/container/Notes/CreateNote/CreateNote.module.css, frontend/src/container/Notes/Notes.js, frontend/src/container/Notes/Notes.module.css, frontend/src/container/Notes/UpdateNote/UpdateNote.js, frontend/src/container/Register/Register.module.css, frontend/src/index.css
closes #82 
add
* no notes message when filtering
modify
* styles for login and register forms
* styles for create and update notes forms
* styles of nav bar
* styles of filter input
* link going to register page
=> #82 modify layouts
